package com.luckwine.trade.dao;

import com.luckwine.trade.entity.TradeCapitalStatement;

public interface TradeCapitalStatementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_capital_statement
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int deleteByPrimaryKey(String capSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_capital_statement
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int insert(TradeCapitalStatement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_capital_statement
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int insertSelective(TradeCapitalStatement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_capital_statement
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    TradeCapitalStatement selectByPrimaryKey(String capSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_capital_statement
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int updateByPrimaryKeySelective(TradeCapitalStatement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_capital_statement
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int updateByPrimaryKey(TradeCapitalStatement record);
}