package com.luckwine.trade.dao;

import com.luckwine.trade.entity.TradeCart;

public interface TradeCartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_cart
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_cart
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int insert(TradeCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_cart
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int insertSelective(TradeCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_cart
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    TradeCart selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_cart
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int updateByPrimaryKeySelective(TradeCart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_cart
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int updateByPrimaryKey(TradeCart record);
}