package com.luckwine.trade.dao;

import com.luckwine.trade.entity.TradeSubOrder;

import java.util.List;

public interface TradeSubOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int deleteByPrimaryKey(String subOrderCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int insert(TradeSubOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int insertSelective(TradeSubOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    List<TradeSubOrder> selectByPrimaryKey(String subOrderCode);

    List<TradeSubOrder> selectByMainOrderCode(String mainOrderCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int updateByPrimaryKeySelective(TradeSubOrder record);

    int updateByMainCodeSelective(TradeSubOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int updateByPrimaryKey(TradeSubOrder record);
}