package com.luckwine.trade.dao;

import com.luckwine.trade.entity.TradeMainOrder;

public interface TradeMainOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_main_order
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int deleteByPrimaryKey(String mainOrderCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_main_order
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int insert(TradeMainOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_main_order
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int insertSelective(TradeMainOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_main_order
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    TradeMainOrder selectByPrimaryKey(String mainOrderCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_main_order
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int updateByPrimaryKeySelective(TradeMainOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_main_order
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    int updateByPrimaryKey(TradeMainOrder record);
}