@startuml
luckwine_portal_web -> luckwine_portal_service: 发送短信请求
luckwine_portal_service --> luckwine_synthesize: 调用综合域短信发送接口

luckwine_synthesize -> aliyun: 调用阿里云短信服务
luckwine_synthesize <-- aliyun: 返回结果

luckwine_portal_service <-- luckwine_synthesize: 返回结果
luckwine_portal_web <-- luckwine_portal_service: 返回结果
@enduml