package com.luckwine.trade.entity;

import lombok.Data;
import lombok.ToString;

import javax.persistence.Id;
import java.util.Date;

@Data
@ToString(callSuper = true)
public class TradeCart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_cart.id
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    @Id
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_cart.login_account
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    private String loginAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_cart.goods_id
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    private String goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_cart.biz_code
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    private String bizCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_cart.count
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_cart.create_time
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_cart.update_time
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_cart.id
     *
     * @return the value of trade_cart.id
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_cart.id
     *
     * @param id the value for trade_cart.id
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_cart.login_account
     *
     * @return the value of trade_cart.login_account
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_cart.login_account
     *
     * @param loginAccount the value for trade_cart.login_account
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount == null ? null : loginAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_cart.goods_id
     *
     * @return the value of trade_cart.goods_id
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_cart.goods_id
     *
     * @param goodsId the value for trade_cart.goods_id
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_cart.biz_code
     *
     * @return the value of trade_cart.biz_code
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    public String getBizCode() {
        return bizCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_cart.biz_code
     *
     * @param bizCode the value for trade_cart.biz_code
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    public void setBizCode(String bizCode) {
        this.bizCode = bizCode == null ? null : bizCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_cart.count
     *
     * @return the value of trade_cart.count
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_cart.count
     *
     * @param count the value for trade_cart.count
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_cart.create_time
     *
     * @return the value of trade_cart.create_time
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_cart.create_time
     *
     * @param createTime the value for trade_cart.create_time
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_cart.update_time
     *
     * @return the value of trade_cart.update_time
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_cart.update_time
     *
     * @param updateTime the value for trade_cart.update_time
     *
     * @mbg.generated Tue Sep 25 19:46:51 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}