server:
  port: 3333

spring:
  # Redis
  redis:
    host: 192.168.85.128
  #Elasticsearch
  data:
    elasticsearch:
      client:
        reactive:
          endpoints:
            - 192.168.85.128:9200

portal:
  # ES
  elasticsearch:
    nodeClient: 192.168.85.128:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: true

dubbo:
  registry:
    address: nacos://192.168.85.128:8848
  consumer:
    group: dev
  provider:
    group: dev
