spring:
  profiles:
    active: dev
  # Redis
  redis:
    host: 192.168.85.128
    password:
    # 数据库索引 默认0
    database: 0
    port: 6379
    timeout: 3000
  #Elasticsearch
  # 文件大小上传配置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  cache:
    type: redis


# 忽略鉴权url
ignored:
  urls:
  - /portal/customer/register
  - /portal/goods/computer
  - /portal/goods/detail
  - /portal/ad/**
  - /portal/common/**
  - /swagger-ui.html
  - /swagger-resources/**
  - /swagger/**
  - /actuator/**
  - /**/v2/api-docs
  - /**/*.js
  - /**/*.css
  - /**/*.png
  - /**/*.ico

# Swagger界面内容配置
swagger:
  title: portal system API接口文档
  description: portal Api Documentation
  version: 1.0.1
  termsOfServiceUrl: https://th15817161961.github.io/readme/
  contact:
    name: Howell
    url: https://th15817161961.github.io/readme/
    email: th15817161961@gmail.com


portal:
  # 全局限流
  rateLimit:
    enable: true
    # 每1秒内
    timeout: 1000
    # 总限制100个请求
    limit: 100
  # token过期时间（分钟）
  tokenExpireTime: 120
  # 用户选择保存登录状态对应token过期时间（天）
  saveLoginTime: 7
  # 限制用户登陆错误次数（次）
  loginTimeLimit: 10
  # 错误超过次数后多少分钟后才能继续登录（分钟）
  loginAfterTime: 10
  endpoint:
  accessKeyId:
  accessKeySecret:
  ossPath:
  bucketName:
  ossUrlPath:
  # ES
  elasticsearch:
    nodeClient: 192.168.85.128:9200
  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
  logRecord:
    es: true

dubbo:
  application:
    name: luckwine-portal-service
    version: 1.0.0
    qos-enable: false
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 6000
    version: 1.0.0
    check: true
    file: ./.dubbo/luckwine_portal_registry
  scan:
    base-packages: com.luckwine.portal
  consumer:
    timeout: 6000
    check: false
    filter: dubboLogFilter,dubboValidationFilter,-validation
    version: 1.0.0
    validation: true