spring:
  profiles:
    active: dev


# 配置文件加密key
jasypt:
  encryptor:
    password: luckwine_customer


# Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.luckwine.customer.model.base
  typeEnumsPackage: com.luckwine.customer.model.base
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


dubbo:
  application:
    name: luckwine-customer
    version: 1.0.0
  protocol:
    port: 28032
    status: server
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 6000
    version: 1.0.0
    check: true
    file: ./.dubbo/luckwine_customer_registry
  scan:
    base-packages: com.luckwine.customer
  provider:
    version: 1.0.0
    timeout: 6000
    filter: dubboLogFilter
  consumer:
    filter: dubboLogFilter
    version: 1.0.0
    check: false

management:
  info:
    git:
      mode: full
    build:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true
    redis:
      enabled: true
    diskspace:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      enabled: true
      show-details: always
    info:
      enabled: true