@startuml
title: 支付单对账
start
repeat
 partition 导入数据  {
  : 1. 生成批次号 对账日期 + 供应商
     例如:  20181010_alipay
    按批次号查询是否存在， 如果存在则跳号 20181010_alipay_HHmmss
     例如：  20181010_alipay_101101
     **入库批次表**;
  : 2.下载**(T-1日)**供应商对账文件
    批量导入redis (采用Pipelined形式导入Set集合);
  :3.导入**(T-1日)对应供应商的支付成功的**支付单;
    }
    partition 对账 {
  : 4.redis diff 对比 支付单与  供应商订单的差异
     记录为 **短款**订单;
    :5. redis diff 对比 供应商订单 与 支付单的差异
     记录为 **长款**订单;
    :6.取出长款与短款的支付单号交集记录为 **差额**;
    :7.将 短款，长款， 差额  按批次号入库 **差错表**;
    note right
      **"长款归公,短款自赔"**:普遍的财务制度
      短款: 我方支付成功,供应商无记录 (**涉嫌赔付**)
      长款: 我方无记录,供应商支付成功
      差额: 我方金额与供应商金额不一致
   end note

    }
repeat while(等待下次任务(每天凌晨5点执行))
stop
@enduml