@startuml
title: 订单同步稽核

start
repeat
  : 查询**待同步支付单**
  1.1天前~截止当前时间1分钟前
  2.支付单状态为: **成功**
  3.同步状态为: **等待同步 or 同步失败**
  4.小于最大同步次数;
  : 调用**订单同步接口**发起同步;
if (同步成功) then (yes)
  :更新,然后任务结束;
else (no)
  : 任务结束等待下次轮询;
endif
repeat while(等待下次任务(10分钟一次))
stop

@enduml